In [ ]:
pip install dnspython

Requirement already satisfied: dnspython in /usr/local/lib/python3.6/dist-packages (2.0.0)

In [110]:
from pymongo import MongoClient
from random import randint
import pandas as pd 
import math
import ssl
#Step 1: Connect to MongoDB - Note: Change connection string as needed
client = MongoClient(host=['mongodb+srv://Manpreet:Chahal123@cluster0.mzino.mongodb.net/test'],ssl_cert_reqs=ssl.CERT_NONE,
                     document_class=dict, tz_aware=False, connect=True)
db=client.ReuterDb
print(db)

Database(MongoClient(host=['cluster0-shard-00-01.mzino.mongodb.net:27017', 'cluster0-shard-00-02.mzino.mongodb.net:27017', 'cluster0-shard-00-00.mzino.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', replicaset='atlas-140kfk-shard-0', ssl=True, ssl_cert_reqs=<VerifyMode.CERT_NONE: 0>), 'ReuterDb')

In [111]:
dataList=[]
words=["Canada", "rain", "cold", "hot"]
i=0
news=[]
mycol = db["NewsData"]

In [112]:
for x in mycol.find(): 
    news.append(x["body"])
news=news[:2000]

# Part 2

In [113]:

dataList=[]

In [114]:
import nltk
nltk.download('punkt')
i=0
for sentence in news:
  count=0
  count1=0
  if isinstance(sentence, str):
    tokens = nltk.word_tokenize(sentence)
    for token in tokens:
      count=count+1
      if token=="Canada":
        count1 = count1+1
  if(count1 > 0):
    data={
    "Index":i,
    "Documents":"Article#"+ str(i),
    "Total Words":count,
    "Frequency":count1}
    dataList.append(data)
  i=i+1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [115]:
print(dataList)

[{'Index': 74, 'Documents': 'Article#74', 'Total Words': 266, 'Frequency': 2}, {'Index': 82, 'Documents': 'Article#82', 'Total Words': 213, 'Frequency': 1}, {'Index': 87, 'Documents': 'Article#87', 'Total Words': 167, 'Frequency': 1}, {'Index': 89, 'Documents': 'Article#89', 'Total Words': 72, 'Frequency': 1}, {'Index': 99, 'Documents': 'Article#99', 'Total Words': 861, 'Frequency': 1}, {'Index': 104, 'Documents': 'Article#104', 'Total Words': 446, 'Frequency': 6}, {'Index': 108, 'Documents': 'Article#108', 'Total Words': 305, 'Frequency': 1}, {'Index': 199, 'Documents': 'Article#199', 'Total Words': 197, 'Frequency': 3}, {'Index': 243, 'Documents': 'Article#243', 'Total Words': 213, 'Frequency': 1}, {'Index': 297, 'Documents': 'Article#297', 'Total Words': 305, 'Frequency': 1}, {'Index': 299, 'Documents': 'Article#299', 'Total Words': 114, 'Frequency': 1}, {'Index': 332, 'Documents': 'Article#332', 'Total Words': 194, 'Frequency': 1}, {'Index': 335, 'Documents': 'Article#335', 'Total Words': 351, 'Frequency': 3}, {'Index': 342, 'Documents': 'Article#342', 'Total Words': 181, 'Frequency': 1}, {'Index': 406, 'Documents': 'Article#406', 'Total Words': 106, 'Frequency': 1}, {'Index': 418, 'Documents': 'Article#418', 'Total Words': 192, 'Frequency': 1}, {'Index': 422, 'Documents': 'Article#422', 'Total Words': 939, 'Frequency': 2}, {'Index': 476, 'Documents': 'Article#476', 'Total Words': 209, 'Frequency': 1}, {'Index': 493, 'Documents': 'Article#493', 'Total Words': 358, 'Frequency': 3}, {'Index': 556, 'Documents': 'Article#556', 'Total Words': 219, 'Frequency': 1}, {'Index': 600, 'Documents': 'Article#600', 'Total Words': 753, 'Frequency': 1}, {'Index': 626, 'Documents': 'Article#626', 'Total Words': 85, 'Frequency': 1}, {'Index': 644, 'Documents': 'Article#644', 'Total Words': 115, 'Frequency': 2}, {'Index': 686, 'Documents': 'Article#686', 'Total Words': 339, 'Frequency': 7}, {'Index': 698, 'Documents': 'Article#698', 'Total Words': 274, 'Frequency': 1}, {'Index': 700, 'Documents': 'Article#700', 'Total Words': 164, 'Frequency': 1}, {'Index': 760, 'Documents': 'Article#760', 'Total Words': 513, 'Frequency': 1}, {'Index': 773, 'Documents': 'Article#773', 'Total Words': 191, 'Frequency': 1}, {'Index': 776, 'Documents': 'Article#776', 'Total Words': 121, 'Frequency': 1}, {'Index': 788, 'Documents': 'Article#788', 'Total Words': 463, 'Frequency': 2}, {'Index': 813, 'Documents': 'Article#813', 'Total Words': 987, 'Frequency': 1}, {'Index': 874, 'Documents': 'Article#874', 'Total Words': 222, 'Frequency': 1}, {'Index': 920, 'Documents': 'Article#920', 'Total Words': 434, 'Frequency': 2}, {'Index': 928, 'Documents': 'Article#928', 'Total Words': 516, 'Frequency': 1}, {'Index': 932, 'Documents': 'Article#932', 'Total Words': 333, 'Frequency': 1}, {'Index': 958, 'Documents': 'Article#958', 'Total Words': 168, 'Frequency': 1}, {'Index': 1022, 'Documents': 'Article#1022', 'Total Words': 98, 'Frequency': 2}, {'Index': 1178, 'Documents': 'Article#1178', 'Total Words': 78, 'Frequency': 2}, {'Index': 1187, 'Documents': 'Article#1187', 'Total Words': 329, 'Frequency': 1}, {'Index': 1195, 'Documents': 'Article#1195', 'Total Words': 96, 'Frequency': 1}, {'Index': 1225, 'Documents': 'Article#1225', 'Total Words': 400, 'Frequency': 1}, {'Index': 1229, 'Documents': 'Article#1229', 'Total Words': 289, 'Frequency': 4}, {'Index': 1244, 'Documents': 'Article#1244', 'Total Words': 79, 'Frequency': 1}, {'Index': 1295, 'Documents': 'Article#1295', 'Total Words': 518, 'Frequency': 1}, {'Index': 1341, 'Documents': 'Article#1341', 'Total Words': 227, 'Frequency': 1}, {'Index': 1357, 'Documents': 'Article#1357', 'Total Words': 95, 'Frequency': 1}, {'Index': 1379, 'Documents': 'Article#1379', 'Total Words': 30, 'Frequency': 1}, {'Index': 1438, 'Documents': 'Article#1438', 'Total Words': 305, 'Frequency': 2}, {'Index': 1495, 'Documents': 'Article#1495', 'Total Words': 99, 'Frequency': 1}, {'Index': 1511, 'Documents': 'Article#1511', 'Total Words': 45, 'Frequency': 1}, {'Index': 1592, 'Documents': 'Article#1592', 'Total Words': 227, 'Frequency': 1}, {'Index': 1593, 'Documents': 'Article#1593', 'Total Words': 145, 'Frequency': 1}, {'Index': 1655, 'Documents': 'Article#1655', 'Total Words': 843, 'Frequency': 1}, {'Index': 1700, 'Documents': 'Article#1700', 'Total Words': 85, 'Frequency': 1}, {'Index': 1715, 'Documents': 'Article#1715', 'Total Words': 251, 'Frequency': 3}, {'Index': 1754, 'Documents': 'Article#1754', 'Total Words': 490, 'Frequency': 1}, {'Index': 1822, 'Documents': 'Article#1822', 'Total Words': 191, 'Frequency': 2}]

In [116]:
canadaDF = pd.DataFrame(dataList)
canadaDF = canadaDF.sort_values(by=['Frequency'], ascending=False)
canadaDF

    Index     Documents  Total Words  Frequency
23    686   Article#686          339          7
5     104   Article#104          446          6
41   1229  Article#1229          289          4
54   1715  Article#1715          251          3
7     199   Article#199          197          3
12    335   Article#335          351          3
18    493   Article#493          358          3
0      74    Article#74          266          2
16    422   Article#422          939          2
47   1438  Article#1438          305          2
37   1178  Article#1178           78          2
36   1022  Article#1022           98          2
32    920   Article#920          434          2
29    788   Article#788          463          2
22    644   Article#644          115          2
56   1822  Article#1822          191          2
15    418   Article#418          192          1
6     108   Article#108          305          1
39   1195  Article#1195           96          1
40   1225  Article#1225          400          1
4      99    Article#99          861          1
42   1244  Article#1244           79          1
43   1295  Article#1295          518          1
44   1341  Article#1341          227          1
45   1357  Article#1357           95          1
46   1379  Article#1379           30          1
3      89    Article#89           72          1
48   1495  Article#1495           99          1
49   1511  Article#1511           45          1
50   1592  Article#1592          227          1
51   1593  Article#1593          145          1
52   1655  Article#1655          843          1
53   1700  Article#1700           85          1
2      87    Article#87          167          1
55   1754  Article#1754          490          1
38   1187  Article#1187          329          1
8     243   Article#243          213          1
17    476   Article#476          209          1
35    958   Article#958          168          1
14    406   Article#406          106          1
19    556   Article#556          219          1
20    600   Article#600          753          1
21    626   Article#626           85          1
13    342   Article#342          181          1
11    332   Article#332          194          1
24    698   Article#698          274          1
25    700   Article#700          164          1
26    760   Article#760          513          1
27    773   Article#773          191          1
1      82    Article#82          213          1
10    299   Article#299          114          1
30    813   Article#813          987          1
31    874   Article#874          222          1
9     297   Article#297          305          1
33    928   Article#928          516          1
34    932   Article#932          333          1
28    776   Article#776          121          1

In [117]:
df.to_csv('SemanticAnalysis_Step18_Part2.csv', index = False)



# Part 3

In [118]:
for data in dataList:
  data["relativeFrequency"]=data["Frequency"]/data["Total Words"]

In [119]:
canadaRel = pd.DataFrame(dataList)
canadaRel = canadaRel.sort_values(by=['relativeFrequency'], ascending=False)
canadaRel

    Index     Documents  Total Words  Frequency  relativeFrequency
46   1379  Article#1379           30          1           0.033333
37   1178  Article#1178           78          2           0.025641
49   1511  Article#1511           45          1           0.022222
23    686   Article#686          339          7           0.020649
36   1022  Article#1022           98          2           0.020408
22    644   Article#644          115          2           0.017391
7     199   Article#199          197          3           0.015228
3      89    Article#89           72          1           0.013889
41   1229  Article#1229          289          4           0.013841
5     104   Article#104          446          6           0.013453
42   1244  Article#1244           79          1           0.012658
54   1715  Article#1715          251          3           0.011952
21    626   Article#626           85          1           0.011765
53   1700  Article#1700           85          1           0.011765
45   1357  Article#1357           95          1           0.010526
56   1822  Article#1822          191          2           0.010471
39   1195  Article#1195           96          1           0.010417
48   1495  Article#1495           99          1           0.010101
14    406   Article#406          106          1           0.009434
10    299   Article#299          114          1           0.008772
12    335   Article#335          351          3           0.008547
18    493   Article#493          358          3           0.008380
28    776   Article#776          121          1           0.008264
0      74    Article#74          266          2           0.007519
51   1593  Article#1593          145          1           0.006897
47   1438  Article#1438          305          2           0.006557
25    700   Article#700          164          1           0.006098
2      87    Article#87          167          1           0.005988
35    958   Article#958          168          1           0.005952
13    342   Article#342          181          1           0.005525
27    773   Article#773          191          1           0.005236
15    418   Article#418          192          1           0.005208
11    332   Article#332          194          1           0.005155
17    476   Article#476          209          1           0.004785
8     243   Article#243          213          1           0.004695
1      82    Article#82          213          1           0.004695
32    920   Article#920          434          2           0.004608
19    556   Article#556          219          1           0.004566
31    874   Article#874          222          1           0.004505
50   1592  Article#1592          227          1           0.004405
44   1341  Article#1341          227          1           0.004405
29    788   Article#788          463          2           0.004320
24    698   Article#698          274          1           0.003650
9     297   Article#297          305          1           0.003279
6     108   Article#108          305          1           0.003279
38   1187  Article#1187          329          1           0.003040
34    932   Article#932          333          1           0.003003
40   1225  Article#1225          400          1           0.002500
16    422   Article#422          939          2           0.002130
55   1754  Article#1754          490          1           0.002041
26    760   Article#760          513          1           0.001949
33    928   Article#928          516          1           0.001938
43   1295  Article#1295          518          1           0.001931
20    600   Article#600          753          1           0.001328
52   1655  Article#1655          843          1           0.001186
4      99    Article#99          861          1           0.001161
30    813   Article#813          987          1           0.001013

In [120]:
news[1379]

'The Bank of Canada said the   U.S. dollar at\nsoon was 1.3053 compared to\n1.3074 dollars yesterday.\n   The pound sterling rates at noon 2.1130  compared to 2.1147\nyesterday.\n   \n'